Homework 7 task 2
artemiipatov/HomeworksSPbU pull request #25
Opened 2021-11-13 12:18 UTC by artemiipatov

2021-11-21 12:25 UTC, yurii-litvinov requested changes
Местами отступы пробелами, местами табуляциями, сделайте пробелами везде :) В Visual Studio рекомендую включить отображение пробельных символов, это Edit -> Advanced -> View White Space

2021-11-21 12:25 UTC, yurii-litvinov commented on Hw7Task2/Hw7Task2/main.c
> +	if (!parse(&root, file))
Я бы сделал parse принимать строку, для удобства тестирования. Либо имя файла, чтобы она сама его открывала, читала и закрывала. Иначе ни то ни сё — с одной стороны, нам всегда нужен файл, с другой стороны, вызывающему надо файл открыть, дерево создать, файл закрыть. Очень много boilerplate-кода. Можно было просто `Node *tree = parse(fileName);`

2021-11-21 12:25 UTC, yurii-litvinov commented on Hw7Task2/Hw7Task2/parseTree.c
> +            (*root)->rightSon = newRoot;
Тут бы ещё проверить, что (*root)->rightSon не занят ещё (хоть условие и обещает, что выражение корректно, но почему нет?)

2021-11-21 12:25 UTC, yurii-litvinov commented on Hw7Task2/Hw7Task2/parseTree.c
> +    int secondOperand = eval(root->rightSon);
const-ов бы побольше

2021-11-21 12:25 UTC, yurii-litvinov commented on Hw7Task2/Hw7Task2/parseTree.c
> +        }
Нуу, `printf("( %c", root->value);`

2021-11-21 12:25 UTC, yurii-litvinov commented on Hw7Task2/Hw7Task2/tests.c
> +	return isEmpty(root);
В случае успеха файл не закрывается :)

2021-11-21 18:34 UTC, artemiipatov commented on Hw7Task2/Hw7Task2/tests.c
> +	return isEmpty(root);
Закрывается на 20 строке.

2021-11-21 18:39 UTC, yurii-litvinov commented on Hw7Task2/Hw7Task2/tests.c
> +	return isEmpty(root);
Хм, и правда. Но зачем он тогда ещё раз закрывается на 23-й?

2021-11-21 19:07 UTC, artemiipatov commented on Hw7Task2/Hw7Task2/tests.c
> +	return isEmpty(root);
Это уже поправил.

2021-12-06 18:50 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2021-12-07 06:28 UTC, merged